### ISSUE TITLE
Crear archivos de configuración para distintos ambientes en el front-end (local y producción)

### ISSUE THREAD

**Issue by krostyle** [krostyle/themis-tracker-front#13]
### Descripción:
Crear archivos de configuración para los distintos ambientes en el front-end (local y producción). Estos archivos de configuración serán utilizados para manejar las dependencias y configuraciones del front-end según el ambiente.

### Acceptance Criteria:
- Crear archivos de configuración para ambientes locales y de producción.
- Incluir configuraciones necesarias como URL de la API, claves de acceso, etc.
- Asegurarse de que los archivos de configuración sean fáciles de mantener y extender.
- Verificar que los archivos de configuración sean accesibles desde los componentes del front-end.
- Documentar el proceso para agregar nuevas configuraciones o modificar las existentes.

### Tasks:
- [ ] Definir la estructura y el contenido de los archivos de configuración para los ambientes locales y de producción.
- [ ] Crear los archivos de configuración en el directorio adecuado del front-end.
- [ ] Incluir las configuraciones necesarias para el front-end en los archivos.
- [ ] Asegurarse de que las configuraciones sean accesibles y utilizables por los componentes del front-end.
- [ ] Documentar el proceso de configuración y mantenimiento de estos archivos.
