### ISSUE TITLE
Crear Footer

### ISSUE THREAD

**Issue by krostyle** [krostyle/themis-tracker-front#2]
**Description:**
Desarrollar el footer de la aplicación web siguiendo un diseño básico. El footer debe incluir enlaces a las páginas principales, iconos de redes sociales, y la información de contacto de la empresa.

**Acceptance Criteria:**
- El footer debe ser responsive y funcionar bien en dispositivos móviles y de escritorio.
- Incluir enlaces a "Inicio", "Acerca de", "Servicios", "Contacto".
- Incluir iconos de redes sociales con enlaces a las cuentas de la empresa.
- Mostrar la información de contacto de la empresa (dirección, teléfono, correo electrónico).
- Utilizar estilos básicos y consistentes con el resto de la app.

**Tasks:**
- [x] Implementar estructura HTML del footer
- [x] Aplicar estilos CSS básicos al footer
- [x] Añadir enlaces a las páginas principales
- [ ] Incluir iconos de redes sociales con enlaces
- [ ] Mostrar la información de contacto de la empresa
- [ ] Revisar la responsividad del footer en diferentes dispositivos
---

**Comment by krostyle** [comment]
Se sube rama
